---
title: "ESPN NFL Power Rankings"
resource_files:
- ARI.png
- ATL.png
- BAL.png
- BUF.png
- CAR.png
- CHI.png
- CIN.png
- CLE.png
- DAL.png
- DEN.png
- DET.png
- GB.png
- HOU.png
- IND.png
- JAC.png
- KC.png
- LAC.png
- LAR.png
- LV.png
- MIA.png
- MIN.png
- NE.png
- NO.png
- NYG.png
- NYJ.png
- PHI.png
- PIT.png
- SEA.png
- SF.png
- TB.png
- TEN.png
- WAS.png
runtime: shiny
output: flexdashboard::flex_dashboard
---


```{r global, include = F}
# setup, calling packages
suppressMessages(library(dplyr))
suppressMessages(library(tidyr))
suppressMessages(library(lubridate))
suppressMessages(library(ggplot2))
suppressMessages(library(stringr))
suppressMessages(library(ggimage))

# init helpers
source("helpers.R")

# read in data
nfl2020_raw <- read.csv("NFL_Rankings_2020.csv")

PLAYOFF_MAPS = list("all" = 0:6,
                    "made" = 1:6,
                    "missed" = 0,
                    "wc" = 5:6,
                    "div" = 1:4,
                    "bye" = 1:2,
                    "hf" = 1
                    )


#create wrangled NFL 2020 data frame
nfl2020_wrangled <- nfl2020_raw%>% #start with nfl2020_raw dataframe
  mutate(Week0=PreSeason)%>% #duplicate PreSeason column with name Week0
  pivot_longer(., paste0("Week",0:18), names_to = "Week", values_to = "Rank") %>% #pivot weeks to long form
  filter(!is.na(Rank)) %>% #filter out any row where the Rank column is NA
  mutate(Week=as.numeric(str_replace_all(Week, "Week", "")), #replace "WeekX" in each cell with just "X", converted to a numeric value
         # MainColor = paste0("#",toupper(MainColor)), #specifies the hex color for each team
         png_local = paste0(TeamCode,".png")) # create a column of .png file names for each team's logo
 

```


Sidebar {.sidebar}
=====================================

```{r}
# shiny inputs defined here

sliderInput('max_week', h4('Maximum Week'), min = 0, max = 18, value = 18, step = 1, round = T, dragRange = TRUE)

selectInput("conf", label = h4("Conference"), 
    choices = list("All" = "All", "AFC" = "AFC", "NFC" = "NFC"), 
    selected = "All")

selectInput("div", label = h4("Division"), 
    choices = list("All" = "All", "North" = "North", "South" = "South",
                   "East" = "East", "West" = "West"), 
    selected = "All")




checkboxGroupInput("yoff", label = h4("2019 Playoffs"),
                   choices = list("All" = "all",
                                  "Made Playoffs" = "made",
                                  "Missed Playoffs" = "missed",
                                  "Wild Card" = "wc",
                                  "Division Winner" = "div",
                                  "Bye" = "bye",
                                  "Home Field Advantage" = "hf"
                    ),
                   selected = 'all'
                   )


filtered_df <- reactive({
  
  
  playoff_seed_vec = lapply(input$yoff, function(x) PLAYOFF_MAPS[[x]]) %>%
    unlist() %>%
    unique()
  
  if (input$conf == 'All'){
    
    result = subset_teams(df = nfl2020_wrangled, 
                          conference = NULL,
                          division = NULL,
                          playoff_seed = playoff_seed_vec)
    
  }else if (input$div == 'All'){
    
    result = subset_teams(df = nfl2020_wrangled, 
                          conference = input$conf,
                          division = NULL,
                          playoff_seed = playoff_seed_vec)
    
  }else{
    
    result = subset_teams(df = nfl2020_wrangled, 
                          conference = input$conf,
                          division = input$div,
                          playoff_seed = playoff_seed_vec)
    
  }
  
  
  result
  
})


```



Week-by-Week
=====================================  
    
```{r}



renderPlot(
  ranking_by_week(filtered_df() %>% filter(Week <= input$max_week))
)

```
   
Preseason Comparison
=====================================     
    
```{r}
renderPlot(
  compare_preseason(filtered_df(), min(input$max_week, max(filtered_df()$Week)))
)

```
